'use client';
import {useState,useEffect,useRef} from 'react';
import {Package,Check,SlidersHorizontal,Wrench,LifeBuoy,BarChart3,Download,Server,MessageSquare} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
import {translate} from '@/lib/i18n';
import type {Lang,Product} from '@/lib/catalog';
import {toast} from 'sonner';
type API=(path:string,body?:unknown)=>Promise<any>;
export type ServiceChoice={tier:string;sector?:string;product?:Product};
const sectors=['sto','salon','shop','studio','other'];
const statuses=['new','contacted','quoted','in_progress','done','declined'];
const tierKey=(tier:string)=>tier==='support'?'installSupport':tier;
const money=(n:number)=>new Intl.NumberFormat('ru-RU').format(n)+' ₸';
function Pick({value,onChange,options,label}:{value:string;onChange:(v:string)=>void;options:string[][];label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger className="picker" aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{options.map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select>}
export function BusinessPacks({lang,products,onOpen,onRequest}:{lang:Lang;products:Product[];onOpen:(p:Product)=>void;onRequest:(s:ServiceChoice)=>void}){
 const t=(k:string)=>translate(lang,k),[wizard,setWizard]=useState(false);
 return <section className="business-packs"><div className="section-heading"><div><span className="eyebrow">BOTSTORE / BUSINESS</span><h2>{t('packsTitle')}</h2><p>{t('packsHint')}</p></div><button className="button outline" onClick={()=>setWizard(true)}><SlidersHorizontal size={18}/>{t('finder')}</button></div><div className="pack-grid">{sectors.slice(0,4).map(sector=>{const p=products.find(x=>x.id==='pack-'+sector);return p?<article key={sector}><span className="pack-marker"><Package size={22}/>{t(sector)}</span><h3>{p.content[lang].name}</h3><p>{p.content[lang].description}</p><div><strong>{money(p.price)}</strong><button className="small-button" onClick={()=>onOpen(p)}>{t('details')}</button></div></article>:null})}</div><SolutionFinder open={wizard} onClose={()=>setWizard(false)} lang={lang} products={products} onOpen={onOpen} onRequest={onRequest}/></section>;
}
function SolutionFinder({open,onClose,lang,products,onOpen,onRequest}:{open:boolean;onClose:()=>void;lang:Lang;products:Product[];onOpen:(p:Product)=>void;onRequest:(s:ServiceChoice)=>void}){
 const t=(k:string)=>translate(lang,k),[step,setStep]=useState(0),[sector,setSector]=useState('sto'),[goal,setGoal]=useState('fullPack'),[help,setHelp]=useState('self');
 useEffect(()=>{if(open)setStep(0)},[open]);
 const id=goal==='accounting'?'sheets-crm':goal==='siteGoal'?'business-website':goal==='orderFlow'?'telegram-orders':goal==='booking'?(sector==='salon'||sector==='studio'?'pack-'+sector:sector==='sto'?'sto-booking':'custom-request'):'pack-'+sector;
 const recommended=products.find(p=>p.id===id);
 return <Dialog open={open} onOpenChange={o=>{if(!o)onClose()}}><DialogContent className="store-dialog"><DialogTitle>{t('finder')}</DialogTitle><DialogDescription>{t('finderHint')}</DialogDescription><div className="finder-progress" aria-label={`${Math.min(step+1,3)} / 3`}>{[0,1,2].map(n=><span key={n} className={step>=n?'filled':''}/>)}</div>{step<3?<><span className="eyebrow">{step+1} / 3</span><h3>{t(step===0?'sector':step===1?'goal':'helpLevel')}</h3><div className="finder-options">{(step===0?sectors:step===1?['booking','orderFlow','accounting','siteGoal','fullPack']:['self','install','support']).map(v=><button key={v} className={(step===0?sector:step===1?goal:help)===v?'selected':''} aria-pressed={(step===0?sector:step===1?goal:help)===v} onClick={()=>step===0?setSector(v):step===1?setGoal(v):setHelp(v)}>{t(tierKey(v))}</button>)}</div><div className="dialog-bottom">{step>0?<button className="button outline" onClick={()=>setStep(step-1)}>{t('back')}</button>:<span/>}<button className="button" onClick={()=>setStep(step+1)}>{t(step===2?'findResult':'next')}</button></div></>:<div className="finder-result"><Check/><h3>{t('recommendation')}</h3>{recommended?<><h4>{recommended.content[lang].name}</h4><p>{recommended.content[lang].description}</p><strong>{money(recommended.price)}</strong><button className="button full" onClick={()=>{onClose();onOpen(recommended)}}>{t('details')}</button>{help!=='self'&&<button className="button outline full" onClick={()=>{onClose();onRequest({tier:help,sector,product:recommended})}}>{t(tierKey(help))}</button>}</>:<button className="button full" onClick={()=>{onClose();onRequest({tier:'custom',sector})}}>{t('requestService')}</button>}<button className="text-button" onClick={()=>setStep(0)}>{t('restart')}</button></div>}</DialogContent></Dialog>;
}
export function ServiceTiers({lang,product,onBuy,onRequest}:{lang:Lang;product:Product;onBuy:()=>void;onRequest:(s:ServiceChoice)=>void}){
 const t=(k:string)=>translate(lang,k);return <section className="service-tiers"><h3>{t('chooseHelp')}</h3><div className="tier-grid">{[['self',Package,'selfHint'],['install',Wrench,'installHint'],['support',LifeBuoy,'supportHint']].map(([tier,Icon,hint]:any)=><article key={tier}><Icon size={22}/><h4>{t(tierKey(tier))}</h4><p>{t(hint)}</p><strong>{tier==='self'?money(product.price):t('quoteFirst')}</strong><button className={'button '+(tier==='self'?'':'outline')} onClick={()=>tier==='self'?onBuy():onRequest({tier,product,sector:product.id.startsWith('pack-')?product.id.slice(5):'other'})}>{t(tier==='self'?(product.price===0?'getFree':'buy'):'requestService')}</button></article>)}</div></section>;
}
export function ServiceCTA({lang,onRequest}:{lang:Lang;onRequest:(s:ServiceChoice)=>void}){const t=(k:string)=>translate(lang,k);return <section className="service-cta"><article><MessageSquare size={25}/><h2>{t('customTitle')}</h2><p>{t('customHint')}</p><button className="button" onClick={()=>onRequest({tier:'custom'})}>{t('requestService')}</button></article><article><Server size={25}/><h2>{t('hosting')}</h2><p>{t('hostingHint')}</p><button className="button outline" onClick={()=>onRequest({tier:'hosting'})}>{t('requestService')}</button></article></section>}
export function ServiceRequestForm({choice,lang,api,onClose}:{choice:ServiceChoice;lang:Lang;api:API;onClose:()=>void}){
 const t=(k:string)=>translate(lang,k),[id]=useState(()=>crypto.randomUUID()),[name,setName]=useState(''),[contact,setContact]=useState(''),[message,setMessage]=useState(''),[sector,setSector]=useState(choice.sector||'other'),[consent,setConsent]=useState(false),[website,setWebsite]=useState(''),[busy,setBusy]=useState(false),[sent,setSent]=useState(false),[error,setError]=useState('');
 return <Dialog open onOpenChange={o=>{if(!o&&!busy)onClose()}}><DialogContent className="store-dialog" showCloseButton={!busy}><DialogTitle>{t(sent?'requestSent':tierKey(choice.tier))}</DialogTitle><DialogDescription>{t(sent?'requestSentHint':'noLoginRequest')}</DialogDescription>{sent?<div className="request-success"><div className="success-circle"><Check size={30}/></div><label>{t('requestId')}<code>{id}</code></label><button className="button outline" onClick={async()=>{try{await navigator.clipboard.writeText(id);toast.success(t('copied'))}catch{toast.error(t('unavailable'))}}}>{t('copy')}</button><button className="button" onClick={onClose}>{t('done')}</button></div>:<form className="sub-form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await api('service-requests',{id,name,contact,message,sector,tier:choice.tier,productId:choice.product?.id,language:lang,consent,website});setSent(true)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>{choice.product&&<div className="order-summary"><Package/><b>{choice.product.content[lang].name}</b></div>}<p className="notice">{t('quoteNotice')}</p><div className="form-grid"><label>{t('requestName')}<input autoComplete="name" required minLength={2} maxLength={100} value={name} onChange={e=>setName(e.target.value)}/></label><label>{t('requestContact')}<input autoComplete="email" required maxLength={200} value={contact} onChange={e=>setContact(e.target.value)}/></label></div><small>{t('requestContactHint')}</small><label>{t('sector')}<Pick label={t('sector')} value={sector} onChange={setSector} options={sectors.map(v=>[v,t(v)])}/></label><label>{t('requestMessage')}<textarea required minLength={10} maxLength={3000} rows={4} value={message} onChange={e=>setMessage(e.target.value)}/></label><div className="form-trap" aria-hidden="true"><label>Website<input tabIndex={-1} autoComplete="off" value={website} onChange={e=>setWebsite(e.target.value)}/></label></div><label className="checkbox-label"><Checkbox checked={consent} onCheckedChange={v=>setConsent(v===true)}/>{t('requestConsent')}</label>{error&&<p className="notice" role="alert">{t(error)}</p>}<button className="button full" disabled={busy||!consent}>{t(busy?'saving':'requestService')}</button></form>}</DialogContent></Dialog>;
}
export function RequestsPanel({lang,api,admin=false}:{lang:Lang;api:API;admin?:boolean}){
 const t=(k:string)=>translate(lang,k),[rows,setRows]=useState<any[]|null>(null),[status,setStatus]=useState('all'),[error,setError]=useState(''),[active,setActive]=useState<any>(null),[busy,setBusy]=useState(false),generation=useRef(0);
 const load=async()=>{const n=++generation.current;try{const d=await api('service-requests'+(admin&&status!=='all'?'?status='+status:''));if(n===generation.current){setRows(d.requests);setError('')}}catch(e){if(n===generation.current)setError((e as Error).message)}};
 useEffect(()=>{void load();return()=>{generation.current++}},[api,status,admin]);
 return <section className="growth-panel"><div className="panel-top"><h2><Wrench size={22}/>{t('serviceRequests')}</h2><div className="row-actions">{admin&&<Pick label={t('filterStatus')} value={status} onChange={setStatus} options={['all',...statuses].map(s=>[s,t(s)])}/>}<button className="button outline" onClick={()=>void load()}>{t('refresh')}</button></div></div>{error?<p className="notice" role="alert">{t(error)}</p>:rows===null?<p>{t('loading')}</p>:!rows.length?<p className="page-empty panel">{t('empty')}</p>:<div className="request-list">{rows.map(row=><article key={row.id}><div><span className={'status '+row.status}>{t(row.status)}</span><h3>{t(tierKey(row.tier))} · {t(row.sector)}</h3><small>{row.id.slice(0,8)} · {new Date(row.created_at).toLocaleDateString()}</small>{admin&&<><p><b>{row.name}</b> · {row.contact}</p><p className="request-message">{row.message}</p></>}{row.quote!==null&&<p>{t('quote')}: <b>{money(row.quote)}</b></p>}{row.deadline&&<p>{t('deadline')}: {row.deadline}</p>}</div>{admin&&<button className="button outline" onClick={()=>setActive({...row})}>{t('edit')}</button>}</article>)}</div>}<p className="muted">{t('requestListLimit')}</p><Dialog open={!!active} onOpenChange={o=>{if(!o&&!busy)setActive(null)}}><DialogContent className="store-dialog"><DialogTitle>{t('serviceRequests')}</DialogTitle><DialogDescription>{active?.id}</DialogDescription>{active&&<form className="sub-form" onSubmit={async e=>{e.preventDefault();setBusy(true);try{await api('service-requests/'+active.id,{status:active.status,quote:active.quote,deadline:active.deadline,note:active.note,updated_at:active.updated_at});setActive(null);await load();toast.success(t('saved'))}catch(e){toast.error(t((e as Error).message))}finally{setBusy(false)}}}><b>{active.name} · {active.contact}</b><p className="request-message">{active.message}</p><p>{t('category')}: {t(active.sector)} · {active.language.toUpperCase()}{active.product_id?' · '+active.product_id:''}</p><label>{t('status')}<Pick label={t('status')} value={active.status} onChange={status=>setActive({...active,status})} options={statuses.map(s=>[s,t(s)])}/></label><div className="form-grid"><label>{t('quote')}<input type="number" min={0} max={10000000} step={1} value={active.quote??''} onChange={e=>setActive({...active,quote:e.target.value===''?null:Number(e.target.value)})}/></label><label>{t('deadline')}<input maxLength={100} value={active.deadline} onChange={e=>setActive({...active,deadline:e.target.value})}/></label></div><label>{t('internalNote')}<textarea rows={4} maxLength={3000} value={active.note} onChange={e=>setActive({...active,note:e.target.value})}/></label><p className="notice">{t('noAutoContact')}</p><button className="button" disabled={busy}>{t(busy?'saving':'save')}</button></form>}</DialogContent></Dialog></section>;
}
export function AnalyticsPanel({lang,api}:{lang:Lang;api:API}){
 const t=(k:string)=>translate(lang,k),[data,setData]=useState<any>(null),[error,setError]=useState('');const load=()=>api('analytics').then(d=>{setData(d);setError('')}).catch(e=>setError(e.message));useEffect(()=>{void load()},[api]);
 const keys=['views','checkouts','orders','paid','free','revenue'],labels=['views','checkouts','orders','paidCount','freeCount','revenue'];
 const totals=Object.fromEntries(keys.map(k=>[k,data?.rows.reduce((sum:number,row:any)=>sum+row[k],0)||0]));
 function download(){const escape=(value:unknown)=>'"'+String(value).replace(/^[\s=+@-]/,"'$&").replaceAll('"','""')+'"';const text='\uFEFF'+[[t('name'),...labels.map(t)],...data.rows.map((r:any)=>[r.content[lang].name,...keys.map(k=>r[k])])].map(row=>row.map(escape).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='BotStore-sales-30-days.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),5000)}
 return <section className="growth-panel"><div className="panel-top"><div><h2><BarChart3 size={22}/>{t('analytics')}</h2><p>{t('last30')}</p></div><div className="row-actions"><button className="button outline" onClick={()=>void load()}>{t('refresh')}</button><button className="button" disabled={!data} onClick={download}><Download size={16}/>{t('exportCsv')}</button></div></div>{error?<p className="notice" role="alert">{t(error)}</p>:!data?<p>{t('loading')}</p>:<><div className="analytics-stats">{keys.map((k,i)=><article key={k}><span>{t(labels[i])}</span><strong>{k==='revenue'?money(totals[k]):totals[k]}</strong></article>)}</div><p className="body-copy">{t('analyticsHint')}</p><p className="muted">{t('analyticsCohort')}</p><div className="table-shell"><Table><TableHeader><TableRow><TableHead>{t('name')}</TableHead>{labels.map(k=><TableHead key={k}>{t(k)}</TableHead>)}</TableRow></TableHeader><TableBody>{data.rows.map((r:any)=><TableRow key={r.id}><TableCell>{r.content[lang].name}</TableCell>{keys.map(k=><TableCell key={k}>{k==='revenue'?money(r[k]):r[k]}</TableCell>)}</TableRow>)}</TableBody></Table></div><h3>{t('serviceRequests')}</h3><div className="request-counts">{statuses.map(s=><span key={s}>{t(s)} <b>{data.requests.find((r:any)=>r.status===s)?.count||0}</b></span>)}</div></>}</section>;
}
export function useCatalogAnalytics(productId:string|undefined,checkout:boolean){
 const [allowed,setAllowed]=useState(false);useEffect(()=>{try{setAllowed(localStorage.getItem('botstore-analytics')==='yes')}catch{}},[]);
 useEffect(()=>{if(!allowed||!productId||navigator.doNotTrack==='1'||(navigator as any).globalPrivacyControl)return;try{let session=sessionStorage.getItem('botstore-session');if(!session){session=crypto.randomUUID();sessionStorage.setItem('botstore-session',session)}void fetch('/api/catalog-events',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({productId,session,kind:checkout?'checkout':'view',consent:true})}).catch(()=>{})}catch{}},[allowed,productId,checkout]);
 return {allowed,setAllowed:(value:boolean)=>{setAllowed(value);try{localStorage.setItem('botstore-analytics',value?'yes':'no');if(!value)sessionStorage.removeItem('botstore-session')}catch{}}};
}
