import {balances,validateInstall,zipFiles} from './commerce';
import {paymentReady,startPayment,paymentCallback} from './payments';
import {installFiles} from './install-files';
import {salesRoute} from './sales-api';
import {ensureBusinessPacks} from './catalog-sync';
import {db,bucket,adminEmail,kaspiTransfer} from './db';
import {catalog} from './catalog';
import {bundles} from './bundles';
class HttpError extends Error{constructor(public status:number,message:string){super(message)}}
const fail=(status:number,msg:string):never=>{throw new HttpError(status,msg)};
const json=(x:unknown,status=200)=>Response.json(x,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
const decode=(p:any,priv=false)=>{const out={...p,content:JSON.parse(p.content)};if(!priv)delete out.file_key;return out};
async function identity(req:Request){const id=req.headers.get('oai-authenticated-user-id'),email=req.headers.get('oai-authenticated-user-email');if(!id||!email)return null;let name=email;try{if(req.headers.get('oai-authenticated-user-full-name-encoding')==='percent-encoded-utf-8')name=decodeURIComponent(req.headers.get('oai-authenticated-user-full-name')||email)}catch{}return {id,email,name,admin:!!adminEmail()&&email.toLowerCase()===adminEmail()}}
function requireUser(u:any){if(!u)fail(401,'signin');return u}
function requireAdmin(u:any){requireUser(u);if(!u.admin)fail(403,'forbidden')}
async function body(req:Request){if(Number(req.headers.get('content-length')||0)>100000)fail(413,'tooLarge');const text=await req.text();if(text.length>100000)fail(413,'tooLarge');try{return JSON.parse(text)}catch{fail(400,'invalid')}}
function str(v:unknown,max=2000){if(typeof v!=='string'||v.length>max)fail(400,'invalid');return (v as string).trim()}
function validDemoUrl(value:string){if(!value)return true;try{const url=new URL(value);if(url.protocol!=='https:'||url.username||url.password||url.port)return false;return ((url.hostname==='www.youtube.com'||url.hostname==='youtube.com')&&(url.pathname==='/watch'&&/^[A-Za-z0-9_-]{11}$/.test(url.searchParams.get('v')||'')||/^\/shorts\/[A-Za-z0-9_-]{11}$/.test(url.pathname)))||(url.hostname==='youtu.be'&&/^\/[A-Za-z0-9_-]{11}$/.test(url.pathname))||(['vimeo.com','www.vimeo.com'].includes(url.hostname)&&/^\/\d+$/.test(url.pathname))}catch{return false}}
function validKaspiLink(value:string){try{const u=new URL(value);return u.protocol==='https:'&&u.hostname==='pay.kaspi.kz'&&u.pathname.split('/').filter(Boolean).length>0&&!u.username&&!u.password&&!u.port&&!u.hash}catch{return false}}
const transferReady=()=>!!(kaspiTransfer().card&&kaspiTransfer().phone);
const kaspiReady=(c:any)=>c.kaspiEnabled===true&&validKaspiLink(c.kaspiUrl||'')&&!!c.kaspiMerchant?.trim();
async function config(){const row=await db().prepare('SELECT value FROM settings WHERE key = ?').bind('business').first<any>();return row?JSON.parse(row.value):{businessName:'BotStore',contactEmail:'',payment:{kk:'',ru:'',en:''},terms:{kk:'',ru:'',en:''},enabled:false}}
async function log(u:any,action:string,target:string){await db().prepare('INSERT INTO audit (id,actor,action,target,created_at) VALUES (?,?,?,?,?)').bind(crypto.randomUUID(),u.email,action,target,Date.now()).run()}
export async function handle(req:Request){try{return await route(req)}catch(e){if(e instanceof HttpError)return json({error:e.message},e.status);console.error('BotStore API',e);return json({error:'unavailable'},503)}}
async function route(req:Request):Promise<Response>{const url=new URL(req.url),path=url.pathname.replace(/^\/api\/?/,'').split('/').filter(Boolean);if(path[0]==='payment'&&path[1]==='result')return paymentCallback(req);const u=await identity(req),method=req.method;
const salesResponse=await salesRoute(req,path,u);if(salesResponse)return salesResponse;
if(!['GET','HEAD'].includes(method)){const origin=req.headers.get('origin');if(!origin||origin!==url.origin)fail(403,'forbidden');if(!u)fail(401,'signin')}
if(path[0]==='bootstrap'&&method==='GET'){
 await ensureBusinessPacks();const cfg=await config();let fav:any[]=[];
 if(u){await db().prepare('INSERT INTO users (id,email,name,created_at) VALUES (?,?,?,?) ON CONFLICT(id) DO UPDATE SET email=excluded.email,name=excluded.name').bind(u.id,u.email,u.name,Date.now()).run();fav=(await db().prepare('SELECT product_id FROM favorites WHERE user_id=?').bind(u.id).all<any>()).results;}
 const result=await db().prepare("SELECT * FROM products WHERE status='published' ORDER BY created_at,id").all<any>();
 return json({user:u,products:result.results.map(p=>decode(p)),favorites:fav.map(x=>x.product_id),settings:{...cfg,commissionBps:cfg.commissionBps??1500,paymentReady:paymentReady(),kaspiTransfer:kaspiTransfer()}});
}
if(path[0]==='initialize'&&method==='POST'){
 requireAdmin(u);const now=Date.now();await db().batch(catalog.map(p=>db().prepare('INSERT OR IGNORE INTO products (id,owner_id,category,price,content,status,file_key,filename,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?)').bind(p.id,u!.id,p.category,p.price,JSON.stringify(p.content),'published',p.file_key,p.filename,now,now)));await log(u,'initialize','catalog');return json({ok:true});
}
if(path[0]==='favorites'&&method==='POST'){
 requireUser(u);const data=await body(req);const id=str(data.productId,100);if(!await db().prepare("SELECT id FROM products WHERE id=? AND status='published'").bind(id).first())fail(404,'notFound');
 if(data.active===true)await db().prepare('INSERT OR IGNORE INTO favorites (user_id,product_id) VALUES (?,?)').bind(u!.id,id).run();else if(data.active===false)await db().prepare('DELETE FROM favorites WHERE user_id=? AND product_id=?').bind(u!.id,id).run();else fail(400,'invalid');return json({ok:true});
}
if(path[0]==='orders'&&path.length===1){requireUser(u);
 if(method==='GET'){const r=await db().prepare('SELECT * FROM orders WHERE user_id=? ORDER BY created_at DESC LIMIT 500').bind(u!.id).all<any>();return json({orders:r.results.map(p=>decode(p))})}
 if(method==='POST'){
 const data=await body(req),id=str(data.productId,100);if(data.accepted!==true)fail(400,'termsRequired');
 const p=await db().prepare("SELECT * FROM products WHERE id=? AND status='published'").bind(id).first<any>();if(!p)fail(404,'notFound');if(!p.file_key)fail(409,'noFile');
 const cfg=await config();if(p.price>0&&(!cfg.enabled||!cfg.contactEmail||!['kk','ru','en'].every(l=>cfg.terms[l]?.trim()&&(transferReady()||kaspiReady(cfg)||cfg.payment[l]?.trim()))))fail(409,'paymentsUnavailable');
 const now=Date.now(),oid=crypto.randomUUID();const fee=u!.admin&&p.owner_id===u!.id?0:Math.floor(p.price*(cfg.commissionBps??1500)/10000);await db().prepare('INSERT INTO orders (id,user_id,product_id,seller_id,price,content,file_key,filename,status,reference,created_at,updated_at,fee) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(user_id,product_id) DO UPDATE SET price=excluded.price,fee=excluded.fee,content=excluded.content,file_key=excluded.file_key,filename=excluded.filename,status=excluded.status,reference=excluded.reference,updated_at=excluded.updated_at WHERE orders.status=\'cancelled\'').bind(oid,u!.id,p.id,p.owner_id,p.price,p.content,p.file_key,p.filename,p.price===0?'paid':'pending','',now,now,fee).run();
 const order=await db().prepare('SELECT * FROM orders WHERE user_id=? AND product_id=?').bind(u!.id,p.id).first<any>();return json({order:decode(order)});
 }
}
if(path[0]==='orders'&&path[1]){requireUser(u);const o=await db().prepare('SELECT * FROM orders WHERE id=? AND user_id=?').bind(path[1],u!.id).first<any>();if(!o)fail(404,'notFound');
 if(path[2]==='download'&&method==='GET'){
 if(o.status!=='paid')fail(403,'notPaid');let response:Response;
 if(o.file_key.startsWith('builtin:')){const encoded=bundles[o.file_key];if(!encoded)fail(404,'noFile');const bytes=Uint8Array.from(atob(encoded),c=>c.charCodeAt(0));response=new Response(bytes)}else{const file=await bucket().get(o.file_key);if(!file)fail(404,'noFile');response=new Response(file!.body)}
 response.headers.set('Content-Type','application/zip');response.headers.set('Content-Disposition',`attachment; filename="botstore-${o.product_id.replace(/[^a-zA-Z0-9-]/g,'')}.zip"`);response.headers.set('Cache-Control','private, no-store');response.headers.set('X-Content-Type-Options','nosniff');return response;
 }
 if(path[2]==='reference'&&method==='POST'){const b=await body(req),reference=str(b.reference,300);if(reference.length<3)fail(400,'invalid');const result=await db().prepare("UPDATE orders SET reference=?,status='review',updated_at=? WHERE id=? AND user_id=? AND status='pending'").bind(reference,Date.now(),o.id,u!.id).run();if(!result.meta.changes)fail(409,'conflict');return json({ok:true})}
}
if(path[0]==='checkout'&&method==='POST'){requireUser(u);const b=await body(req);const o=await db().prepare('SELECT * FROM orders WHERE id=? AND user_id=?').bind(str(b.orderId,100),u!.id).first<any>();if(!o)fail(404,'notFound');try{return json(await startPayment(o,b.language))}catch(e){return json({error:e instanceof Error&&['paymentsUnavailable','conflict'].includes(e.message)?e.message:'paymentUnavailable'},409)}}
if(path[0]==='product-info'&&method==='GET'){
 const id=path[1]||'';const p=await db().prepare("SELECT id FROM products WHERE id=? AND status='published'").bind(id).first();if(!p)fail(404,'notFound');const r=await db().prepare('SELECT rating,body,created_at FROM reviews WHERE product_id=? ORDER BY created_at DESC LIMIT 50').bind(id).all();return json({reviews:r.results});
}
if(path[0]==='reviews'&&method==='POST'){requireUser(u);const b=await body(req),id=str(b.productId,100),text=str(b.body,1000);if(!Number.isInteger(b.rating)||b.rating<1||b.rating>5||text.length<3)fail(400,'invalid');const o=await db().prepare("SELECT id FROM orders WHERE product_id=? AND user_id=? AND status='paid'").bind(id,u!.id).first();if(!o)fail(403,'notPaid');await db().prepare('INSERT INTO reviews (id,user_id,product_id,rating,body,created_at) VALUES (?,?,?,?,?,?) ON CONFLICT(user_id,product_id) DO UPDATE SET rating=excluded.rating,body=excluded.body,created_at=excluded.created_at').bind(crypto.randomUUID(),u!.id,id,b.rating,text,Date.now()).run();return json({ok:true});}
if(path[0]==='tickets'){
 requireUser(u);if(method==='GET'&&!path[1]){const r=await db().prepare(u!.admin?'SELECT t.*,u.email FROM tickets t LEFT JOIN users u ON u.id=t.user_id ORDER BY updated_at DESC LIMIT 200':'SELECT * FROM tickets WHERE user_id=? ORDER BY updated_at DESC LIMIT 200');return json({tickets:(await (u!.admin?r:r.bind(u!.id)).all()).results})}
 if(method==='POST'&&!path[1]){const b=await body(req),orderId=str(b.orderId,100),subject=str(b.subject,160),message=str(b.message,4000);if(subject.length<3||message.length<3)fail(400,'invalid');if(!await db().prepare('SELECT id FROM orders WHERE id=? AND user_id=?').bind(orderId,u!.id).first())fail(404,'notFound');const recent=await db().prepare('SELECT COUNT(*) AS count FROM tickets WHERE user_id=? AND created_at>?').bind(u!.id,Date.now()-3600000).first<any>();if(recent.count>=10)fail(429,'rateLimit');const id=crypto.randomUUID(),now=Date.now();await db().batch([db().prepare('INSERT INTO tickets (id,user_id,order_id,subject,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?)').bind(id,u!.id,orderId,subject,'open',now,now),db().prepare('INSERT INTO messages (id,ticket_id,author_id,is_admin,body,created_at) VALUES (?,?,?,?,?,?)').bind(crypto.randomUUID(),id,u!.id,0,message,now)]);return json({ok:true,id});}
 if(path[1]){const ticket=await db().prepare('SELECT * FROM tickets WHERE id=?').bind(path[1]).first<any>();if(!ticket||(!u!.admin&&ticket.user_id!==u!.id))fail(404,'notFound');if(method==='GET'){const m=await db().prepare('SELECT body,is_admin,created_at FROM messages WHERE ticket_id=? ORDER BY created_at LIMIT 200').bind(ticket.id).all();return json({ticket,messages:m.results})}if(method==='POST'){const b=await body(req);if(b.close===true){requireAdmin(u);await db().prepare("UPDATE tickets SET status='closed',updated_at=? WHERE id=?").bind(Date.now(),ticket.id).run();return json({ok:true})}const message=str(b.message,4000);if(message.length<1)fail(400,'invalid');const recent=await db().prepare('SELECT COUNT(*) AS count FROM messages WHERE ticket_id=? AND created_at>?').bind(ticket.id,Date.now()-60000).first<any>();if(recent.count>=10)fail(429,'rateLimit');await db().batch([db().prepare('INSERT INTO messages (id,ticket_id,author_id,is_admin,body,created_at) VALUES (?,?,?,?,?,?)').bind(crypto.randomUUID(),ticket.id,u!.id,u!.admin?1:0,message,Date.now()),db().prepare("UPDATE tickets SET status='open',updated_at=? WHERE id=?").bind(Date.now(),ticket.id)]);return json({ok:true})}}
}
if(path[0]==='finance'&&method==='GET'){requireUser(u);const all=u!.admin&&url.searchParams.get('all')==='1';let q=db().prepare(all?'SELECT p.*,u.email FROM payouts p LEFT JOIN users u ON u.id=p.seller_id ORDER BY created_at DESC LIMIT 200':'SELECT * FROM payouts WHERE seller_id=? ORDER BY created_at DESC LIMIT 200');return json({balances:await balances(all?undefined:u!.id),payouts:(await (all?q:q.bind(u!.id)).all()).results,commissionBps:(await config()).commissionBps??1500});}
if(path[0]==='payouts'&&method==='POST'){requireAdmin(u);const b=await body(req),seller=str(b.sellerId,100),reference=str(b.reference,300);if(!Number.isInteger(b.amount)||b.amount<=0||reference.length<3||b.confirmed!==true)fail(400,'invalid');const r=await db().prepare("INSERT INTO payouts (id,seller_id,amount,reference,created_at) SELECT ?,?,?,?,? WHERE ? <= (SELECT COALESCE(SUM(price-fee),0) FROM orders WHERE seller_id=? AND status='paid') - (SELECT COALESCE(SUM(amount),0) FROM payouts WHERE seller_id=?)").bind(crypto.randomUUID(),seller,b.amount,reference,Date.now(),b.amount,seller,seller).run();if(!r.meta.changes)fail(409,'insufficientBalance');await log(u,'payout:recorded',seller);return json({ok:true});}
if(path[0]==='install'&&path[1]){requireUser(u);const o=await db().prepare("SELECT * FROM orders WHERE id=? AND user_id=? AND status='paid'").bind(path[1],u!.id).first<any>();if(!o||!Object.hasOwn(installFiles,o.product_id)||o.file_key!=='builtin:'+o.product_id)fail(403,'notPaid');if(method==='POST'){let c;try{c={...validateInstall(await body(req)),sector:o.product_id.replace('pack-','')}}catch{fail(400,'invalid')}await db().prepare('INSERT INTO installations (order_id,user_id,config,updated_at) VALUES (?,?,?,?) ON CONFLICT(order_id) DO UPDATE SET config=excluded.config,updated_at=excluded.updated_at').bind(o.id,u!.id,JSON.stringify(c),Date.now()).run();return json({ok:true})}const row=await db().prepare('SELECT config FROM installations WHERE order_id=? AND user_id=?').bind(o.id,u!.id).first<any>();if(path[2]==='download'&&method==='GET'){if(!row)fail(400,'setupRequired');const bytes=zipFiles({...installFiles[o.product_id],[o.product_id==='sto-booking'?'config.json':'sto-booking/config.json']:JSON.stringify(JSON.parse(row.config),null,2)});return new Response(bytes,{headers:{'Content-Type':'application/zip','Content-Disposition':'attachment; filename="BotStore-configured.zip"','Cache-Control':'private, no-store'}})}if(method==='GET')return json({config:row?JSON.parse(row.config):null});}

if(path[0]==='upload'&&method==='POST'){
 requireUser(u);if(!req.headers.get('content-type')?.startsWith('application/zip'))fail(400,'zipOnly');if(Number(req.headers.get('content-length')||0)>15*1024*1024)fail(413,'tooLarge');const bytes=await req.arrayBuffer();if(bytes.byteLength>15*1024*1024||bytes.byteLength<4)fail(413,'tooLarge');const sig=new Uint8Array(bytes);if(sig[0]!==80||sig[1]!==75||sig[2]!==3||sig[3]!==4)fail(400,'zipOnly');const key='products/'+crypto.randomUUID()+'.zip';const filename='template.zip';await bucket().put(key,bytes,{httpMetadata:{contentType:'application/zip'}});try{await db().prepare('INSERT INTO files (key,owner_id,filename,size,created_at) VALUES (?,?,?,?,?)').bind(key,u!.id,filename,bytes.byteLength,Date.now()).run()}catch(e){await bucket().delete(key);throw e}return json({key,filename,size:bytes.byteLength});
}
if(path[0]==='seller'&&method==='GET'){requireUser(u);const p=await db().prepare('SELECT * FROM products WHERE owner_id=? ORDER BY created_at DESC LIMIT 500').bind(u!.id).all<any>();const sales=await db().prepare("SELECT product_id,COUNT(*) AS count,SUM(price) AS revenue FROM orders WHERE seller_id=? AND status='paid' GROUP BY product_id").bind(u!.id).all();return json({products:p.results.map(p=>decode(p,true)),sales:sales.results})}
if(path[0]==='products'&&method==='POST'){
 requireUser(u);const data=await body(req),id=data.id?str(data.id,100):crypto.randomUUID(),existing=await db().prepare('SELECT * FROM products WHERE id=?').bind(id).first<any>();if(existing&&existing.owner_id!==u!.id&&!u!.admin)fail(403,'forbidden');
 if(!['telegram','sheets','website','bundle'].includes(data.category)||!Number.isInteger(data.price)||data.price<0||data.price>10000000)fail(400,'invalid');
 const demoUrl=str(data.demo_url||'',1000);if(!validDemoUrl(demoUrl))fail(400,'demoUrlInvalid');
 const content:any={};for(const l of ['kk','ru','en']){const c=data.content?.[l];if(!c)fail(400,'translationsRequired');content[l]={name:str(c.name,120),description:str(c.description,2000),features:str(c.features,2000),requirements:str(c.requirements,2000)};if(!content[l].name||!content[l].description||!content[l].requirements)fail(400,'translationsRequired')}
 const fileKey=str(data.file_key||'',200);if(fileKey&&fileKey!==existing?.file_key){const file=await db().prepare('SELECT * FROM files WHERE key=? AND owner_id=?').bind(fileKey,u!.id).first();if(!file)fail(403,'forbidden')}
 let status=data.status==='review'?'review':'draft';if(u!.admin&&['draft','review','published','archived'].includes(data.status))status=data.status;
 if(['review','published'].includes(status)&&!fileKey)fail(400,'noFile');const now=Date.now();
 if(existing){if(!Number.isInteger(data.updated_at))fail(409,'conflict');const r=await db().prepare('UPDATE products SET category=?,price=?,content=?,status=?,file_key=?,filename=?,updated_at=?,demo_url=? WHERE id=? AND updated_at=?').bind(data.category,data.price,JSON.stringify(content),status,fileKey,'template.zip',now,demoUrl,id,data.updated_at).run();if(!r.meta.changes)fail(409,'conflict')}
 else await db().prepare('INSERT INTO products (id,owner_id,category,price,content,status,file_key,filename,created_at,updated_at,demo_url) VALUES (?,?,?,?,?,?,?,?,?,?,?)').bind(id,u!.id,data.category,data.price,JSON.stringify(content),status,fileKey,'template.zip',now,now,demoUrl).run();await log(u,'product:'+status,id);return json({ok:true,id});
}
if(path[0]==='admin'){
 requireAdmin(u);
 if(path.length===1&&method==='GET'){
 const [p,o,users,a,stats]=await Promise.all([db().prepare('SELECT * FROM products ORDER BY created_at DESC LIMIT 500').all<any>(),db().prepare('SELECT o.*,u.email AS buyer_email FROM orders o LEFT JOIN users u ON u.id=o.user_id ORDER BY o.created_at DESC LIMIT 500').all<any>(),db().prepare('SELECT id,email,name,created_at FROM users ORDER BY created_at DESC LIMIT 500').all(),db().prepare('SELECT * FROM audit ORDER BY created_at DESC LIMIT 50').all(),db().prepare("SELECT COUNT(*) AS orders,COALESCE(SUM(CASE WHEN status='paid' THEN price ELSE 0 END),0) AS revenue,COALESCE(SUM(CASE WHEN status IN ('pending','review') THEN 1 ELSE 0 END),0) AS pending FROM orders").first()]);return json({products:p.results.map(p=>decode(p,true)),orders:o.results.map(p=>decode(p)),users:users.results,audit:a.results,stats,settings:{...(await config()),commissionBps:(await config()).commissionBps??1500,paymentReady:paymentReady(),kaspiTransfer:kaspiTransfer()}});
 }
 if(path[1]==='order'&&method==='POST'){
 const b=await body(req),id=str(b.id,100);if(!['paid','cancelled','pending'].includes(b.status))fail(400,'invalid');const allowed=b.status==='pending'?"status='review'":"status IN ('pending','review')";const r=await db().prepare(`UPDATE orders SET status=?,updated_at=? WHERE id=? AND ${allowed} ${b.status==='cancelled'?"AND NOT EXISTS (SELECT 1 FROM payments WHERE order_id=orders.id)":"AND NOT EXISTS (SELECT 1 FROM payments WHERE order_id=orders.id AND status IN ('creating','pending'))"}`).bind(b.status,Date.now(),id).run();if(!r.meta.changes)fail(409,'conflict');await log(u,'order:'+b.status,id);return json({ok:true});
 }
 if(path[1]==='settings'&&method==='POST'){
 const b=await body(req),c={businessName:str(b.businessName,120),contactEmail:str(b.contactEmail,200),payment:{} as any,terms:{} as any,enabled:b.enabled===true,kaspiEnabled:b.kaspiEnabled===true,kaspiUrl:str(b.kaspiUrl||'',1000),kaspiMerchant:str(b.kaspiMerchant||'',160),commissionBps:Number.isInteger(b.commissionBps)?b.commissionBps:1500};if(c.kaspiUrl&&!validKaspiLink(c.kaspiUrl))fail(400,'kaspiInvalid');if(c.kaspiEnabled&&!kaspiReady(c))fail(400,'kaspiRequired');if(c.commissionBps<0||c.commissionBps>5000)fail(400,'invalid');if(c.contactEmail&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(c.contactEmail))fail(400,'invalid');for(const l of ['kk','ru','en']){c.payment[l]=str(b.payment?.[l]||'',4000);c.terms[l]=str(b.terms?.[l]||'',8000)}if(c.enabled&&(!c.businessName||!c.contactEmail||!['kk','ru','en'].every(l=>c.terms[l]&&(transferReady()||kaspiReady(c)||c.payment[l]))))fail(400,'settingsRequired');await db().prepare('INSERT INTO settings (key,value) VALUES (?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').bind('business',JSON.stringify(c)).run();await log(u,'settings:update','business');return json({ok:true});
 }
}
return json({error:'notFound'},404);
}
