import {env} from 'cloudflare:workers';
import {createHash,timingSafeEqual} from 'node:crypto';
import {db} from './db';
const vars=()=>env as unknown as Record<string,string>;
export const paymentReady=()=>!!(vars().FREEDOMPAY_MERCHANT_ID&&vars().FREEDOMPAY_SECRET&&vars().PAYMENT_MODE==='live'&&vars().SITE_ORIGIN?.startsWith('https://'));
export function signature(script:string,fields:Record<string,string>,secret:string){return createHash('md5').update([script,...Object.keys(fields).filter(k=>k!=='pg_sig').sort().map(k=>fields[k]),secret].join(';')).digest('hex')}
export function verify(script:string,fields:Record<string,string>,secret:string){const sig=fields.pg_sig||'';if(!/^[a-f0-9]{32}$/.test(sig)||!fields.pg_salt)return false;return timingSafeEqual(Buffer.from(sig),Buffer.from(signature(script,fields,secret)))}
function parseXML(xml:string){if(xml.length>100000||/<!DOCTYPE|<!ENTITY/i.test(xml))throw Error('paymentUnavailable');const result:Record<string,string>={};for(const m of xml.matchAll(/<(pg_[a-z0-9_]+)>([^<]*)<\/\1>/g)){if(m[1] in result)throw Error('paymentUnavailable');result[m[1]]=m[2].replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&apos;/g,"'")}return result;}
function xmlReply(status:string){const f:Record<string,string>={pg_status:status,pg_description:status==='ok'?'Accepted':'Verification failed',pg_salt:crypto.randomUUID().replaceAll('-','')};f.pg_sig=signature('result',f,vars().FREEDOMPAY_SECRET);return new Response('<?xml version="1.0" encoding="utf-8"?><response>'+Object.entries(f).map(([k,v])=>`<${k}>${v}</${k}>`).join('')+'</response>',{headers:{'Content-Type':'application/xml','Cache-Control':'no-store'}})}
export async function startPayment(order:any,lang:string){if(!paymentReady()||order.price<=0||!['pending'].includes(order.status))throw Error('paymentsUnavailable');const old=await db().prepare('SELECT * FROM payments WHERE order_id=?').bind(order.id).first<any>();if(old?.redirect_url&&old.status==='pending')return {url:old.redirect_url};if(old&&old.status!=='failed')throw Error('paymentUnavailable');const now=Date.now();const lock=await db().prepare("INSERT INTO payments (order_id,status,created_at) VALUES (?,'creating',?) ON CONFLICT(order_id) DO UPDATE SET status='creating',created_at=excluded.created_at WHERE payments.status='failed'").bind(order.id,now).run();if(!lock.meta.changes)throw Error('conflict');
const e=vars(),origin=new URL(e.SITE_ORIGIN).origin,fields:Record<string,string>={pg_merchant_id:e.FREEDOMPAY_MERCHANT_ID,pg_order_id:order.id,pg_amount:order.price.toFixed(2),pg_currency:'KZT',pg_description:'BotStore '+order.id.slice(0,8),pg_salt:crypto.randomUUID().replaceAll('-',''),pg_request_method:'POST',pg_result_url:origin+'/api/payment/result',pg_check_url:'',pg_success_url:origin+'/#account',pg_failure_url:origin+'/#account',pg_success_url_method:'AUTOGET',pg_failure_url_method:'AUTOGET',pg_testing_mode:'0',pg_language:lang==='en'?'en':'ru'};fields.pg_sig=signature('init_payment.php',fields,e.FREEDOMPAY_SECRET);
// An ambiguous timeout remains locked: do not silently create another payable transaction.
const r=await fetch('https://api.freedompay.kz/init_payment.php',{method:'POST',body:new URLSearchParams(fields),signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error('paymentUnavailable');const f=parseXML(await r.text());if(!verify('init_payment.php',f,e.FREEDOMPAY_SECRET))throw Error('paymentUnavailable');if(f.pg_status!=='ok'){await db().prepare("UPDATE payments SET status='failed' WHERE order_id=?").bind(order.id).run();throw Error('paymentUnavailable')}const redirect=new URL(f.pg_redirect_url);if(redirect.protocol!=='https:'||redirect.username||redirect.password||!/^\d+$/.test(f.pg_payment_id))throw Error('paymentUnavailable');await db().prepare("UPDATE payments SET payment_id=?,redirect_url=?,status='pending' WHERE order_id=? AND status='creating'").bind(f.pg_payment_id,redirect.href,order.id).run();return {url:redirect.href};}
export async function paymentCallback(req:Request){if(!paymentReady())return new Response('Unavailable',{status:503});if(req.method!=='POST')return new Response('Method not allowed',{status:405});if(Number(req.headers.get('content-length')||0)>20000)return new Response('Too large',{status:413});const raw=await req.text();if(raw.length>20000)return new Response('Too large',{status:413});const form=new URLSearchParams(raw),f:Record<string,string>={};for(const [k,v] of form){if(k in f)return new Response('Duplicate parameter',{status:400});f[k]=v}if(!verify('result',f,vars().FREEDOMPAY_SECRET))return new Response('Invalid signature',{status:403});const o=await db().prepare('SELECT o.*,p.payment_id AS gateway_id FROM orders o JOIN payments p ON p.order_id=o.id WHERE o.id=?').bind(f.pg_order_id||'').first<any>();if(!o||f.pg_payment_id!==o.gateway_id||f.pg_currency!=='KZT'||Number(f.pg_amount)!==o.price||f.pg_testing_mode==='1'||(f.pg_merchant_id&&f.pg_merchant_id!==vars().FREEDOMPAY_MERCHANT_ID))return xmlReply('error');if(f.pg_result==='0'){await db().prepare("UPDATE payments SET status='failed' WHERE order_id=? AND status='pending'").bind(o.id).run();return xmlReply('ok')}if(f.pg_result!=='1'||!['pending','review','paid'].includes(o.status))return xmlReply('error');await db().batch([db().prepare("UPDATE orders SET status='paid',updated_at=? WHERE id=? AND status IN ('pending','review')").bind(Date.now(),o.id),db().prepare("UPDATE payments SET status='paid' WHERE order_id=?").bind(o.id)]);return xmlReply('ok');}
