import { sqliteTable, text, integer, index, uniqueIndex } from 'drizzle-orm/sqlite-core';
export const users=sqliteTable('users',{id:text('id').primaryKey(),email:text('email').notNull(),name:text('name').notNull(),createdAt:integer('created_at').notNull()});
export const products=sqliteTable('products',{id:text('id').primaryKey(),demoUrl:text('demo_url').notNull().default(''),ownerId:text('owner_id').notNull(),category:text('category').notNull(),price:integer('price').notNull(),content:text('content').notNull(),status:text('status').notNull(),fileKey:text('file_key').notNull(),filename:text('filename').notNull(),createdAt:integer('created_at').notNull(),updatedAt:integer('updated_at').notNull()},t=>[index('idx_products_status').on(t.status),index('idx_products_owner').on(t.ownerId)]);
export const orders=sqliteTable('orders',{id:text('id').primaryKey(),userId:text('user_id').notNull(),productId:text('product_id').notNull(),sellerId:text('seller_id').notNull(),fee:integer('fee').notNull().default(0),price:integer('price').notNull(),content:text('content').notNull(),fileKey:text('file_key').notNull(),filename:text('filename').notNull(),status:text('status').notNull(),reference:text('reference').notNull().default(''),createdAt:integer('created_at').notNull(),updatedAt:integer('updated_at').notNull()},t=>[uniqueIndex('idx_orders_user_product').on(t.userId,t.productId),index('idx_orders_status').on(t.status),index('idx_orders_seller').on(t.sellerId),index('idx_orders_created').on(t.createdAt)]);
export const favorites=sqliteTable('favorites',{userId:text('user_id').notNull(),productId:text('product_id').notNull()},t=>[uniqueIndex('idx_favorites_user_product').on(t.userId,t.productId)]);
export const settings=sqliteTable('settings',{key:text('key').primaryKey(),value:text('value').notNull()});
export const files=sqliteTable('files',{key:text('key').primaryKey(),ownerId:text('owner_id').notNull(),filename:text('filename').notNull(),size:integer('size').notNull(),createdAt:integer('created_at').notNull()});
export const audit=sqliteTable('audit',{id:text('id').primaryKey(),actor:text('actor').notNull(),action:text('action').notNull(),target:text('target').notNull(),createdAt:integer('created_at').notNull()});
export const tickets=sqliteTable('tickets',{id:text('id').primaryKey(),userId:text('user_id').notNull(),orderId:text('order_id').notNull(),subject:text('subject').notNull(),status:text('status').notNull().default('open'),createdAt:integer('created_at').notNull(),updatedAt:integer('updated_at').notNull()},t=>[index('idx_tickets_user').on(t.userId)]);
export const messages=sqliteTable('messages',{id:text('id').primaryKey(),ticketId:text('ticket_id').notNull(),authorId:text('author_id').notNull(),isAdmin:integer('is_admin').notNull(),body:text('body').notNull(),createdAt:integer('created_at').notNull()},t=>[index('idx_messages_ticket').on(t.ticketId)]);
export const payouts=sqliteTable('payouts',{id:text('id').primaryKey(),sellerId:text('seller_id').notNull(),amount:integer('amount').notNull(),reference:text('reference').notNull(),createdAt:integer('created_at').notNull()},t=>[index('idx_payouts_seller').on(t.sellerId)]);
export const installations=sqliteTable('installations',{orderId:text('order_id').primaryKey(),userId:text('user_id').notNull(),config:text('config').notNull(),updatedAt:integer('updated_at').notNull()});
export const reviews=sqliteTable('reviews',{id:text('id').primaryKey(),userId:text('user_id').notNull(),productId:text('product_id').notNull(),rating:integer('rating').notNull(),body:text('body').notNull(),createdAt:integer('created_at').notNull()},t=>[uniqueIndex('idx_reviews_user_product').on(t.userId,t.productId),index('idx_reviews_product').on(t.productId)]);
export const payments=sqliteTable('payments',{orderId:text('order_id').primaryKey(),paymentId:text('payment_id'),redirectUrl:text('redirect_url'),status:text('status').notNull(),createdAt:integer('created_at').notNull()});
export const serviceRequests=sqliteTable('service_requests',{
 id:text('id').primaryKey(),userId:text('user_id'),productId:text('product_id'),tier:text('tier').notNull(),sector:text('sector').notNull(),language:text('language').notNull(),name:text('name').notNull(),contact:text('contact').notNull(),message:text('message').notNull(),status:text('status').notNull().default('new'),quote:integer('quote'),deadline:text('deadline').notNull().default(''),note:text('note').notNull().default(''),createdAt:integer('created_at').notNull(),updatedAt:integer('updated_at').notNull()
},t=>[index('idx_requests_status_created').on(t.status,t.createdAt),index('idx_requests_user_created').on(t.userId,t.createdAt),index('idx_requests_created').on(t.createdAt)]);
export const catalogEvents=sqliteTable('catalog_events',{id:text('id').primaryKey(),productId:text('product_id').notNull(),kind:text('kind').notNull(),session:text('session').notNull(),day:text('day').notNull(),createdAt:integer('created_at').notNull()},t=>[uniqueIndex('idx_events_unique').on(t.productId,t.kind,t.session,t.day),index('idx_events_created').on(t.createdAt)]);
export const requestLimits=sqliteTable('request_limits',{key:text('key').primaryKey(),count:integer('count').notNull(),expiresAt:integer('expires_at').notNull()},t=>[index('idx_limits_expiry').on(t.expiresAt)]);
